### PR TITLE
feat: lint jsdocs

### PR DESCRIPTION
**Pull request by skeggse**
This is mostly to help avoid outdated documentation w.r.t. parameters changing and duplicated types
with Flow.

### CODE REVIEW

**Comment by skeggse** [comment]
>Perhaps this supports auto-fix though?

That's what I'm about to test next!

**Comment by jhoffmanmixmax** [comment]
I like this idea! I can say for sure I've recently pushed code with out of date jsdocs on Task Prio. I keep telling myself I'll hunt down the couple of spots "later tonight" but after 1.5 weeks I still haven't found the time D:

**Comment by shils** [comment]
Adding to what @ghmeier said, I think it would be worth seeing what the migration path would look like for repos like salesforce and google-apis prior to merging this. Then we'd have an idea of the scope and could prioritize prepping them for this change (maybe allowing them to opt-out initially)

**Comment by enricribas** [comment]
I also worry about how we will write JSDocs for things like higher order functions, and dependency injection that JSDocs doesn't support very well. If the linting blocks PRs, there needs to be a way to document everything or a way to go around it for some files.

**Comment by skeggse** [comment]
@enricribas this doesn't require jsdocs for all functions; it doesn't require jsdocs for all parameters. it _does_ try and avoid outdated jsdocs (e.g. I had a parameter and renamed it and now the jsdocs are wrong) and formatting errors. In some ways, this would be a better fit for prettier but it doesn't look like they're on that path anytime soon.

**Comment by bradvogel** [comment]
@skeggse this can be closed?

**Comment by bradvogel** [comment]
closing due to age. Feel free to reopen.

**Pull request closed without merging**
